source 'https://github.com/CocoaPods/Specs.git'

target "QiniuDemo" do
  platform :ios, "7.0"
  
  pod 'QNLibcurl', :path => '../../QNLibcurl'
  pod 'Qiniu',:path => '../'
end

target "QiniuDemoTests" do
#  platform :ios, "7.0"
#  pod 'Qiniu',:path => '../'
end
